# Generated by Django 3.2.9 on 2021-11-06 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='body',
            new_name='password',
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
