# Generated by Django 3.2.9 on 2021-11-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
