# Generated by Django 3.2.9 on 2021-11-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
