# Generated by Django 3.2.9 on 2021-11-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
