# Generated by Django 3.2.9 on 2021-11-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211109_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.TextField(unique=True),
        ),
    ]
