# Generated by Django 3.2.9 on 2021-11-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_login_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.TextField(),
        ),
    ]
