# Generated by Django 3.2.9 on 2021-11-30 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_login_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('appointment_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('method', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('service_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('email', models.TextField(unique=True)),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('address', models.TextField()),
                ('password', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='worker',
            fields=[
                ('worker_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('email', models.TextField(unique=True)),
                ('fname', models.TextField()),
                ('lname', models.TextField()),
                ('password', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('average_rates', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
