# Generated by Django 3.2.9 on 2021-12-10 13:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211210_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to=api.models.upload_to),
        ),
    ]
